# Use via: go.amp.dev/samples
/samples: /documentation/examples/
/docs: /documentation/
/websites: /about/websites
/stories: /about/stories
/stories-best-practices: /documentation/guides-and-tutorials/develop/amp_story_best_practices
/ads: /about/ads
/email: /about/email
/vision-mission: /about/mission-and-vision
/governance: /community/governance
/shopify-apps: https://blog.amp.dev/2019/04/15/shopify-apps-make-amp-easy-and-effective-for-ecommerce
